global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Tournament Microservices
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'tournament-api'
    static_configs:
      - targets: ['tournament-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'elo-service'
    static_configs:
      - targets: ['elo-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'leaderboard-service'
    static_configs:
      - targets: ['leaderboard-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'review-workflow'
    static_configs:
      - targets: ['review-workflow:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'hash-verification'
    static_configs:
      - targets: ['hash-verification:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'team-management'
    static_configs:
      - targets: ['team-management:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'match-scheduling'
    static_configs:
      - targets: ['match-scheduling:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'audit-service'
    static_configs:
      - targets: ['audit-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Infrastructure Services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter (if running)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Application-specific metrics
  - job_name: 'tournament-custom-metrics'
    static_configs:
      - targets: 
        - 'api-gateway:8080'
        - 'tournament-api:8080'
        - 'elo-service:8080'
        - 'leaderboard-service:8080'
    metrics_path: '/metrics/custom'
    scrape_interval: 20s
    scrape_timeout: 10s 