apiVersion: v1
kind: Secret
metadata:
  name: tournament-secrets
  namespace: tournament-service
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values in production
  database-url: cG9zdGdyZXNxbDovL3RvdXJuYW1lbnRfdXNlcjp0b3VybmFtZW50X3Bhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi90b3VybmFtZW50X2Ri
  redis-url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  rabbitmq-url: YW1xcDovL3RvdXJuYW1lbnRfdXNlcjp0b3VybmFtZW50X3Bhc3N3b3JkQHJhYmJpdG1xLXNlcnZpY2U6NTY3Mi8=
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  smtp-user: eW91ci1lbWFpbEBnbWFpbC5jb20=
  smtp-pass: eW91ci1hcHAtcGFzc3dvcmQ=
  api-key: eW91ci1hcGkta2V5LWZvci1wcm9kdWN0aW9u
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: tournament-service
type: Opaque
data:
  username: dG91cm5hbWVudF91c2Vy
  password: dG91cm5hbWVudF9wYXNzd29yZA==
  database: dG91cm5hbWVudF9kYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: tournament-service
type: Opaque
data:
  password: dG91cm5hbWVudF9yZWRpc19wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: tournament-service
type: Opaque
data:
  username: dG91cm5hbWVudF91c2Vy
  password: dG91cm5hbWVudF9wYXNzd29yZA== 